version: '3.8'
services:
  user:
    image: godinson/future-user
    container_name: future_user
    ports:
      - "3001:3001"
    entrypoint: ["/usr/src/app/start.sh" ]
    command: ["node", "dist/main"]
    restart: always
    pull_policy: always
    