apiVersion: v1
kind: Service
metadata:
  name: future-user-service
spec:
  selector:
    app: future-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30000
  type: LoadBalancer