name: Build and push user service

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          envkey_ENCRYPTION_ALGORITHM: ${{ secrets.ENCRYPTION_ALGORITHM }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: godinson/future-user:latest
