name: Build and push user service

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Update env
        run: |
          touch .env
          echo JWT_EXPIRATION=${JWT_EXPIRATION} > .env
          echo JWT_SECRET=${JWT_SECRET} > .env
          echo ENCRYPTION_KEY=${ENCRYPTION_KEY} > .env
          echo ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM} > .env
          cat .env
        env:
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_ALGORITHM: ${{ secrets.ENCRYPTION_ALGORITHM }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: godinson/future-user:latest
